version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - web

  web:
    build: ./docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_list
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -uuser -puserpassword -e 'SHOW TABLES LIKE \"tasks\";' todo_list | grep \"tasks\"" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
